/*
 * Matterhorn API
 *
 * Draft spec for the Matterhorn POC
 *
 * API version: 0.1.0
 * Contact: ozinoveva@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// ExerciseApiService is a service that implents the logic for the ExerciseApiServicer
// This service should implement the business logic for every endpoint for the ExerciseApi API. 
// Include any external packages or services that will be required by this service.
type ExerciseApiService struct {
}

// NewExerciseApiService creates a default api service
func NewExerciseApiService() ExerciseApiServicer {
	return &ExerciseApiService{}
}

// GetExerciseRecords - Get exercise records for a user and a given time range
func (s *ExerciseApiService) GetExerciseRecords(userId int64, startDateTime string, endDateTime string) (interface{}, error) {
	// TODO - update GetExerciseRecords with the required logic for this service method.
	// Add api_exercise_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetExerciseRecords' not implemented")
}

// PostExerciseRecord - Add a new exercise record
func (s *ExerciseApiService) PostExerciseRecord(userId int64, exerciseRecord ExerciseRecord) (interface{}, error) {
	// TODO - update PostExerciseRecord with the required logic for this service method.
	// Add api_exercise_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'PostExerciseRecord' not implemented")
}
