/*
 * Matterhorn API
 *
 * Draft spec for the Matterhorn POC
 *
 * API version: 0.1.0
 * Contact: ozinoveva@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// GoalsApiService is a service that implents the logic for the GoalsApiServicer
// This service should implement the business logic for every endpoint for the GoalsApi API. 
// Include any external packages or services that will be required by this service.
type GoalsApiService struct {
}

// NewGoalsApiService creates a default api service
func NewGoalsApiService() GoalsApiServicer {
	return &GoalsApiService{}
}

// GetCalorieGoal - Get the calorie goal for the user
func (s *GoalsApiService) GetCalorieGoal(userId int64) (interface{}, error) {
	// TODO - update GetCalorieGoal with the required logic for this service method.
	// Add api_goals_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetCalorieGoal' not implemented")
}

// PutCalorieGoal - Update the calorie goal for the user
func (s *GoalsApiService) PutCalorieGoal(userId int64, calorieGoal CalorieGoal) (interface{}, error) {
	// TODO - update PutCalorieGoal with the required logic for this service method.
	// Add api_goals_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'PutCalorieGoal' not implemented")
}
