/*
 * Matterhorn API
 *
 * Draft spec for the Matterhorn POC
 *
 * API version: 0.1.0
 * Contact: ozinoveva@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"database/sql"
	"errors"
	"fmt"
	"log"
	"net/http"

	database "github.com/Matterhorn-Apps/MatterhornApiService/database"
)

// MetricsApiService is a service that implents the logic for the MetricsApiServicer
// This service should implement the business logic for every endpoint for the MetricsApi API.
// Include any external packages or services that will be required by this service.
type MetricsApiService struct {
	db *sql.DB
}

// NewMetricsApiService creates a default api service
func NewMetricsApiService(db *sql.DB) MetricsApiServicer {
	return &MetricsApiService{
		db: db,
	}
}

// GetMetrics - Get the body metrics for the user
func (s *MetricsApiService) GetMetrics(userId int64) (interface{}, *int, error) {
	db := s.db

	// Query the database for matching exercise records
	query := fmt.Sprintf("SELECT Height, Weight, Sex, Age from Users WHERE UserID=%d;", userId)
	readRows, readErr := db.Query(query)
	if readErr != nil {
		if errCode, ok := database.TryExtractMySQLErrorCode(readErr); ok {
			switch *errCode {
			case 1452:
				// User not found
				status := http.StatusNotFound
				return nil, &status, readErr
			}
		}

		log.Printf("Failed to query database: %v", readErr)
		return nil, nil, readErr
	}
	defer readRows.Close()

	var height int64
	var weight float32
	var sex string
	var age int32
	readRows.Next()
	readErr = readRows.Scan(&height, &weight, &sex, &age)
	if readErr != nil {
		if errCode, ok := database.TryExtractMySQLErrorCode(readErr); ok {
			switch *errCode {
			// TODO: Interpret error and attempt to map to appropriate status code
			}
		}

		log.Printf("Failed to read row returned from query: %v", readErr)
		return nil, nil, readErr
	}

	record := BodyMetrics{
		Height: height,
		Weight: weight,
		Sex:    sex,
		Age:    age,
	}

	status := http.StatusOK
	return record, &status, nil
}

// PutMetrics - Update body metrics for the user
func (s *MetricsApiService) PutMetrics(userId int64, bodyMetrics BodyMetrics) (interface{}, *int, error) {
	db := s.db

	if bodyMetrics.Height < 0 {
		status := http.StatusBadRequest
		return nil, &status, errors.New("Invalid body metrics: Height must be non-negative")
	} else if bodyMetrics.Weight < 0 {
		status := http.StatusBadRequest
		return nil, &status, errors.New("Invalid body metrics: Height must be non-negative")
	} else if bodyMetrics.Age < 0 {
		status := http.StatusBadRequest
		return nil, &status, errors.New("Invalid body metrics: Age must be non-negative")
	}

	// Query the database for matching exercise records
	query := fmt.Sprintf(
		"UPDATE Users SET Height = %[2]d, Weight = %[3]f, Sex = '%[4]s', Age = %[5]d WHERE UserID = %[1]d",
		userId, bodyMetrics.Height, bodyMetrics.Weight, bodyMetrics.Sex, bodyMetrics.Age)
	_, readErr := db.Exec(query)
	if readErr != nil {
		if errCode, ok := database.TryExtractMySQLErrorCode(readErr); ok {
			switch *errCode {
			case 1452:
				// User not found
				status := http.StatusNotFound
				return nil, &status, readErr
			}
		}

		log.Printf("Failed to query database: %v", readErr)
		return nil, nil, readErr
	}

	status := http.StatusNoContent
	return bodyMetrics, &status, nil
}
