/*
 * Matterhorn API
 *
 * Draft spec for the Matterhorn POC
 *
 * API version: 0.1.0
 * Contact: ozinoveva@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"
)

// A CountersApiController binds http requests to an api service and writes the service results to the http response
type CountersApiController struct {
	service CountersApiServicer
}

// NewCountersApiController creates a default api controller
func NewCountersApiController(s CountersApiServicer) Router {
	return &CountersApiController{service: s}
}

// Routes returns all of the api route for the CountersApiController
func (c *CountersApiController) Routes() Routes {
	return Routes{
		{
			"GetCounter",
			strings.ToUpper("Get"),
			"/counter",
			c.GetCounter,
		},
	}
}

// GetCounter - Get the current counter value and increment it
func (c *CountersApiController) GetCounter(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetCounter()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
