/*
 * Matterhorn API
 *
 * Draft spec for the Matterhorn POC
 *
 * API version: 0.1.0
 * Contact: ozinoveva@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// FoodApiService is a service that implents the logic for the FoodApiServicer
// This service should implement the business logic for every endpoint for the FoodApi API. 
// Include any external packages or services that will be required by this service.
type FoodApiService struct {
}

// NewFoodApiService creates a default api service
func NewFoodApiService() FoodApiServicer {
	return &FoodApiService{}
}

// GetFoodRecords - Get food records for a user and a given time range
func (s *FoodApiService) GetFoodRecords(userId int64, startDateTime string, endDateTime string) (interface{}, error) {
	// TODO - update GetFoodRecords with the required logic for this service method.
	// Add api_food_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetFoodRecords' not implemented")
}

// PostFoodRecord - Add a new food record
func (s *FoodApiService) PostFoodRecord(userId int64, foodRecord FoodRecord) (interface{}, error) {
	// TODO - update PostFoodRecord with the required logic for this service method.
	// Add api_food_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'PostFoodRecord' not implemented")
}
