/*
 * Matterhorn API
 *
 * Draft spec for the Matterhorn POC
 *
 * API version: 0.1.0
 * Contact: ozinoveva@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"database/sql"
	"log"
)

// ExerciseApiService is a service that implents the logic for the ExerciseApiServicer
// This service should implement the business logic for every endpoint for the ExerciseApi API.
// Include any external packages or services that will be required by this service.
type ExerciseApiService struct {
	db *sql.DB
}

// NewExerciseApiService creates a default api service
func NewExerciseApiService(db *sql.DB) ExerciseApiServicer {
	return &ExerciseApiService{
		db: db,
	}
}

// GetExerciseRecords - Get exercise records for a user and a given time range
func (s *ExerciseApiService) GetExerciseRecords(userId int64, startDateTime string, endDateTime string) (interface{}, error) {
	db := s.db

	// Query the database for matching exercise records
	readRows, readErr := db.Query(
		"SELECT * from ExerciseRecords WHERE ID='%n' AND Timestamp BETWEEN '%s' AND '%s';",
		userId, startDateTime, endDateTime)
	if readErr != nil {
		log.Printf("Failed to query database: %v", readErr)
		return nil, readErr
	}
	defer readRows.Close()

	var records []ExerciseRecord
	var row ExerciseRecord
	for readRows.Next() {
		readErr = readRows.Scan(&row)
		if readErr != nil {
			log.Printf("Failed to read row returned from query: %v", readErr)
			return nil, readErr
		}

		records = append(records, row)
	}

	return records, nil
}

// PostExerciseRecord - Add a new exercise record
func (s *ExerciseApiService) PostExerciseRecord(userId int64, exerciseRecord ExerciseRecord) (interface{}, error) {
	db := s.db

	// Query the database for matching exercise records
	_, readErr := db.Exec(
		"INSERT INTO ExerciseRecords(ID, Calories, Label, Timestamp) VALUES(%n, %n, %s, %s);",
		userId, exerciseRecord.Calories, exerciseRecord.Label, exerciseRecord.Timestamp)
	if readErr != nil {
		log.Printf("Failed to query database: %v", readErr)
		return nil, readErr
	}

	return exerciseRecord, nil
}
