/*
 * Matterhorn API
 *
 * Draft spec for the Matterhorn POC
 *
 * API version: 0.1.0
 * Contact: ozinoveva@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// MetricsApiService is a service that implents the logic for the MetricsApiServicer
// This service should implement the business logic for every endpoint for the MetricsApi API. 
// Include any external packages or services that will be required by this service.
type MetricsApiService struct {
}

// NewMetricsApiService creates a default api service
func NewMetricsApiService() MetricsApiServicer {
	return &MetricsApiService{}
}

// GetMetrics - Get the body metrics for the user
func (s *MetricsApiService) GetMetrics(userId int64) (interface{}, error) {
	// TODO - update GetMetrics with the required logic for this service method.
	// Add api_metrics_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetMetrics' not implemented")
}

// PutMetrics - Update body metrics for the user
func (s *MetricsApiService) PutMetrics(userId int64, bodyMetrics BodyMetrics) (interface{}, error) {
	// TODO - update PutMetrics with the required logic for this service method.
	// Add api_metrics_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'PutMetrics' not implemented")
}
