/*
 * Matterhorn API
 *
 * Draft spec for the Matterhorn POC
 *
 * API version: 0.1.0
 * Contact: ozinoveva@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Counter struct {

	// Unique identifier for the returned counter
	ID int64 `json:"ID"`

	// Current value of the counter
	Value int64 `json:"Value"`
}
