/*
 * Matterhorn API
 *
 * Draft spec for the Matterhorn POC
 *
 * API version: 0.1.0
 * Contact: ozinoveva@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BodyMetrics struct {

	// Height in inches
	Height int64 `json:"height"`

	// Weight in pounds
	Weight float32 `json:"weight"`

	Sex string `json:"sex"`

	// Age in years
	Age int32 `json:"age"`
}
