name: Deploy master

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: '1.14'
    - name: Build
      run: |
        ./build.sh
    - name: Pack
      run: |
        git archive -o source.zip HEAD
    - name: Upload build artifact
      uses: actions/upload-artifact@v1
      with:
        name: deployable
        path: source.zip

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v1
      with:
        name: deployable
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@verboselog
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: MatterhornApiService
        environment_name: Matterhornapiservice-env
        version_label: ${{ github.run_id }}
        region: ${{ secrets.AWS_REGION }}
        deployment_package: ./deployable/source.zip